/**
 * Build script for Ultra editor
 * 
 * Generates embedded config from JSON files and compiles the binary.
 */

import { $ } from "bun";
import * as fs from "fs";
import * as path from "path";

// Step 1: Generate defaults.ts from JSON config files
console.log("Generating embedded config from JSON files...");

const configDir = "./config";
const themesDir = path.join(configDir, "themes");
const outputFile = "./src/config/defaults.ts";

// Read JSON files
const keybindingsJson = fs.readFileSync(
  path.join(configDir, "default-keybindings.json"),
  "utf-8"
);
const settingsJson = fs.readFileSync(
  path.join(configDir, "default-settings.json"),
  "utf-8"
);

// Read BOOT.md
const bootMd = fs.readFileSync(
  path.join(configDir, "BOOT.md"),
  "utf-8"
);

// Parse to validate and re-stringify for clean formatting
const keybindings = JSON.parse(keybindingsJson);
const settings = JSON.parse(settingsJson);

// Read all theme files
const themeFiles = fs.readdirSync(themesDir).filter(f => f.endsWith('.json'));
const themes: Record<string, any> = {};

for (const themeFile of themeFiles) {
  const themeName = themeFile.replace('.json', '');
  const themeJson = fs.readFileSync(path.join(themesDir, themeFile), "utf-8");
  themes[themeName] = JSON.parse(themeJson);
  console.log(`  Loaded theme: ${themeName}`);
}

// Generate TypeScript file
const generatedTs = `/**
 * Default Configuration (Auto-generated)
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edit the JSON files in config/ and run build to regenerate.
 *
 * Generated from:
 *   - config/default-keybindings.json
 *   - config/default-settings.json
 *   - config/themes/*.json
 *   - config/BOOT.md
 */

import type { KeyBinding } from '../input/keymap.ts';
import type { Theme } from '../ui/themes/theme-loader.ts';

export const defaultKeybindings: KeyBinding[] = ${JSON.stringify(keybindings, null, 2)};

export const defaultSettings: Record<string, any> = ${JSON.stringify(settings, null, 2)};

export const defaultThemes: Record<string, Theme> = ${JSON.stringify(themes, null, 2)};

export const defaultBootFile: string = ${JSON.stringify(bootMd)};
`;

fs.writeFileSync(outputFile, generatedTs);
console.log(`Generated ${outputFile}`);

// Step 2: Compile the binary
console.log("Compiling ultra binary...");
// Mark node-pty as external since it may not be installed (we fall back to bun-pty)
await $`bun build --compile --target=bun-darwin-arm64 --external node-pty ./src/index.ts --outfile ultra`;

console.log("Build complete!");
